package com.tech_challenge.medical.infrastructure.llm;

import java.util.List;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;

import com.tech_challenge.medical.domain.summary.ClinicalSummary;
import com.tech_challenge.medical.domain.triage.Confidence;
import com.tech_challenge.medical.domain.triage.Inconsistencies;
import com.tech_challenge.medical.domain.triage.Inconsistency;
import com.tech_challenge.medical.domain.triage.PhysicianNotes;
import com.tech_challenge.medical.domain.triage.RiskFactor;
import com.tech_challenge.medical.domain.triage.RiskFactors;
import com.tech_challenge.medical.domain.triage.TriageLevel;
import com.tech_challenge.medical.domain.triage.TriageResult;

import jakarta.annotation.PostConstruct;

/**
 * Lightweight mock LLM client used when the `mock-llm` Spring profile is active.
 * Returns a deterministic, conservative TriageResult to avoid external API calls.
 */
@Component
@Profile("mock-llm")
public class MockLlmClient implements LlmClient {
    private static final Logger log = LoggerFactory.getLogger(MockLlmClient.class);

    @PostConstruct
    public void init() {
        log.info("MockLlmClient initialized - using mock LLM client for testing purposes.");
    }

    @Override
    public TriageResult analyzeClinicalSummary(ClinicalSummary summary) {
        log.debug("MockLlmClient invoked - returning deterministic triage result");

        return TriageResult.of(
                TriageLevel.MEDIUM,
                RiskFactors.of(List.of(RiskFactor.of("Risk Factor detected in mock analysis"))),
                Inconsistencies.of(List.of(Inconsistency.of("Inconsistency detected in mock analysis"))),
                PhysicianNotes.of("Physician Notes generated by mock LLM client."),
                Confidence.of(0.5)
        );
    }
}
